<?xml version="1.0"?>
<robot name="edumip141" xmlns:xacro="http://ros.org/wiki/xacro">


  <xacro:property name="wheel_separation" value="0.070" />
  <xacro:property name="wheel_radius" value="0.034" />
  <xacro:property name="wheel_width" value="0.010" />
  <xacro:property name="body_height" value="0.1" />
  <xacro:property name="body_width" value="0.050" />
  <xacro:property name="body_length" value="0.035" />
  <xacro:property name="pi" value="3.1415" />


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="green">
    <color rgba="0 0.8 0 1"/>
  </material>

  <material name="red">
    <color rgba="0.8 0 0 1"/>
  </material>


  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </xacro:macro>


  <link name="edumip_body">
    <visual>
      <geometry>
	<box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
	<box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>


  <xacro:macro name="wheel" params="color suffix reflect">

    <link name="wheel${suffix}">
      <visual>
        <!-- origin xyz="0 0 0" rpy="${wheel_separation/2} 0 0" / -->
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="0.4"/>
    </link>
    
    <joint name="joint${suffix}" type="continuous">
      <axis xyz="0 0 1" rpy="0 0 0" />
      <parent link="edumip_body"/>
      <child link="wheel${suffix}"/>
      <origin xyz="0 ${wheel_separation/2*reflect} -${body_height/2-0.005}" rpy="${pi/2} 0 0"/>
    </joint>

  </xacro:macro>


  <xacro:wheel color="green" suffix="L" reflect="-1" />
  <xacro:wheel color="red" suffix="R" reflect="1" />


</robot>
